//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Сведения о дате по представленным документам
 * 
 * <p>Java class for ДатаДокТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ДатаДокТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ПрДень"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="День" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-2"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ПрМесяц"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Месяц" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-2"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Год"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear"&gt;
 *               &lt;minInclusive value="1826"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ДатаДокТип", propOrder = {
    "прДень",
    "день",
    "прМесяц",
    "месяц",
    "год"
})
public class ДатаДокТип {

    @XmlElement(name = "ПрДень")
    protected String прДень;
    @XmlElement(name = "День")
    protected BigInteger день;
    @XmlElement(name = "ПрМесяц")
    protected String прМесяц;
    @XmlElement(name = "Месяц")
    protected BigInteger месяц;
    @XmlElement(name = "Год", required = true)
    protected XMLGregorianCalendar год;

    /**
     * Gets the value of the прДень property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрДень() {
        return прДень;
    }

    /**
     * Sets the value of the прДень property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрДень(String value) {
        this.прДень = value;
    }

    /**
     * Gets the value of the день property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getДень() {
        return день;
    }

    /**
     * Sets the value of the день property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setДень(BigInteger value) {
        this.день = value;
    }

    /**
     * Gets the value of the прМесяц property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрМесяц() {
        return прМесяц;
    }

    /**
     * Sets the value of the прМесяц property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрМесяц(String value) {
        this.прМесяц = value;
    }

    /**
     * Gets the value of the месяц property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getМесяц() {
        return месяц;
    }

    /**
     * Sets the value of the месяц property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setМесяц(BigInteger value) {
        this.месяц = value;
    }

    /**
     * Gets the value of the год property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getГод() {
        return год;
    }

    /**
     * Sets the value of the год property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setГод(XMLGregorianCalendar value) {
        this.год = value;
    }

}
