//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.xmls.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fatalinf.zags.artefacts.x.types._4_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fatalinf.zags.artefacts.x.types._4_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип }
     * 
     */
    public СведЕГРРазд2Тип createСведЕГРРазд2Тип() {
        return new СведЕГРРазд2Тип();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвДокИн }
     * 
     */
    public СведЕГРРазд2Тип.СвДокИн createСведЕГРРазд2ТипСвДокИн() {
        return new СведЕГРРазд2Тип.СвДокИн();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок }
     * 
     */
    public СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок createСведЕГРРазд2ТипСвДокИнЮрЗначДок() {
        return new СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвУведомл }
     * 
     */
    public СведЕГРРазд2Тип.СвУведомл createСведЕГРРазд2ТипСвУведомл() {
        return new СведЕГРРазд2Тип.СвУведомл();
    }

    /**
     * Create an instance of {@link АдрМЖТип }
     * 
     */
    public АдрМЖТип createАдрМЖТип() {
        return new АдрМЖТип();
    }

    /**
     * Create an instance of {@link МестоТип }
     * 
     */
    public МестоТип createМестоТип() {
        return new МестоТип();
    }

    /**
     * Create an instance of {@link УдЛичнФЛПрТип }
     * 
     */
    public УдЛичнФЛПрТип createУдЛичнФЛПрТип() {
        return new УдЛичнФЛПрТип();
    }

    /**
     * Create an instance of {@link УдЛичнФЛСНТип }
     * 
     */
    public УдЛичнФЛСНТип createУдЛичнФЛСНТип() {
        return new УдЛичнФЛСНТип();
    }

    /**
     * Create an instance of {@link ФИОПрТип }
     * 
     */
    public ФИОПрТип createФИОПрТип() {
        return new ФИОПрТип();
    }

    /**
     * Create an instance of {@link ДатаДокТип }
     * 
     */
    public ДатаДокТип createДатаДокТип() {
        return new ДатаДокТип();
    }

    /**
     * Create an instance of {@link АдрРФТип }
     * 
     */
    public АдрРФТип createАдрРФТип() {
        return new АдрРФТип();
    }

    /**
     * Create an instance of {@link ЗасвидТип }
     * 
     */
    public ЗасвидТип createЗасвидТип() {
        return new ЗасвидТип();
    }

    /**
     * Create an instance of {@link СведСвидетТип }
     * 
     */
    public СведСвидетТип createСведСвидетТип() {
        return new СведСвидетТип();
    }

    /**
     * Create an instance of {@link ОрганЗАГСНТип }
     * 
     */
    public ОрганЗАГСНТип createОрганЗАГСНТип() {
        return new ОрганЗАГСНТип();
    }

    /**
     * Create an instance of {@link ОрганЗАГСТип }
     * 
     */
    public ОрганЗАГСТип createОрганЗАГСТип() {
        return new ОрганЗАГСТип();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвДокИн.РеквизИнДок }
     * 
     */
    public СведЕГРРазд2Тип.СвДокИн.РеквизИнДок createСведЕГРРазд2ТипСвДокИнРеквизИнДок() {
        return new СведЕГРРазд2Тип.СвДокИн.РеквизИнДок();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок.Легализация }
     * 
     */
    public СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок.Легализация createСведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализация() {
        return new СведЕГРРазд2Тип.СвДокИн.ЮрЗначДок.Легализация();
    }

    /**
     * Create an instance of {@link СведЕГРРазд2Тип.СвУведомл.СведЗАГСУвед }
     * 
     */
    public СведЕГРРазд2Тип.СвУведомл.СведЗАГСУвед createСведЕГРРазд2ТипСвУведомлСведЗАГСУвед() {
        return new СведЕГРРазд2Тип.СвУведомл.СведЗАГСУвед();
    }

    /**
     * Create an instance of {@link АдрМЖТип.АдрМЖРФ }
     * 
     */
    public АдрМЖТип.АдрМЖРФ createАдрМЖТипАдрМЖРФ() {
        return new АдрМЖТип.АдрМЖРФ();
    }

    /**
     * Create an instance of {@link АдрМЖТип.АдрМЖИн }
     * 
     */
    public АдрМЖТип.АдрМЖИн createАдрМЖТипАдрМЖИн() {
        return new АдрМЖТип.АдрМЖИн();
    }

}
