//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.xmls.types;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Сведения о внесении в ЕГР ЗАГС сведений о документе компетентного органа иностранного государства (Раздел 2) 
 * 
 * <p>Java class for СведЕГРРазд2Тип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СведЕГРРазд2Тип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ПрСвУведомл"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="СвУведомл"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;choice&gt;
 *                       &lt;element name="ПрКодВидУвед"&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                             &lt;enumeration value="1"/&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/simpleType&gt;
 *                       &lt;/element&gt;
 *                       &lt;element name="КодВидУвед" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-5"/&gt;
 *                     &lt;/choice&gt;
 *                     &lt;choice&gt;
 *                       &lt;element name="ПрДатаУвед"&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                             &lt;enumeration value="1"/&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/simpleType&gt;
 *                       &lt;/element&gt;
 *                       &lt;element name="ДатаУвед" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                     &lt;/choice&gt;
 *                     &lt;element name="СведЗАГСУвед"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСТип"/&gt;
 *                               &lt;choice&gt;
 *                                 &lt;element name="ПрФИООтв"&gt;
 *                                   &lt;simpleType&gt;
 *                                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                       &lt;enumeration value="1"/&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/simpleType&gt;
 *                                 &lt;/element&gt;
 *                                 &lt;element name="ФИООтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
 *                               &lt;/choice&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;attribute name="ДатаПринят" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                             &lt;attribute name="ДолжнОтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="СпоcПод" use="required"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                         &lt;enumeration value="1"/&gt;
 *                         &lt;enumeration value="2"/&gt;
 *                         &lt;enumeration value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/attribute&gt;
 *                   &lt;attribute name="КолЛистДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-3" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="СвДокИн"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="ПрКодОКСМ"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                           &lt;enumeration value="1"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="КодОКСМ" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОКСМТип"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element name="НаимСтраны" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
 *                   &lt;element name="РеквизИнДок"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрНаимДокТекст"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="НаимДокТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрНомер"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="Номер" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-100"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрДата"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="ДатаКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                               &lt;element name="ДатаДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрНаимОрган"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="НаимОрган" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="ТипДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-5" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ЮрЗначДок"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрПодпИн"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="СвПодпТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрЗасвидДок"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="ЗасвидДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрЗасвидПеревод"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="ЗасвидПеревод" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="СвОтказЛегализ"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="Легализация"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;choice&gt;
 *                                           &lt;element name="ПрОрганЛегал"&gt;
 *                                             &lt;simpleType&gt;
 *                                               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                                 &lt;enumeration value="1"/&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/simpleType&gt;
 *                                           &lt;/element&gt;
 *                                           &lt;element name="ОрганЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
 *                                         &lt;/choice&gt;
 *                                         &lt;choice&gt;
 *                                           &lt;element name="ПрДатаЛегал"&gt;
 *                                             &lt;simpleType&gt;
 *                                               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                                 &lt;enumeration value="1"/&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/simpleType&gt;
 *                                           &lt;/element&gt;
 *                                           &lt;element name="ДатаЛегал" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                         &lt;/choice&gt;
 *                                         &lt;choice&gt;
 *                                           &lt;element name="ПрНомерЛегал"&gt;
 *                                             &lt;simpleType&gt;
 *                                               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                                 &lt;enumeration value="1"/&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/simpleType&gt;
 *                                           &lt;/element&gt;
 *                                           &lt;element name="НомерЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-25"/&gt;
 *                                         &lt;/choice&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="КолЛистДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-3" /&gt;
 *                           &lt;attribute name="СвОттискПеч" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                 &lt;enumeration value="1"/&gt;
 *                                 &lt;enumeration value="2"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="СвЛегал" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                 &lt;enumeration value="1"/&gt;
 *                                 &lt;enumeration value="2"/&gt;
 *                                 &lt;enumeration value="3"/&gt;
 *                                 &lt;enumeration value="4"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "СведЕГРРазд2Тип", propOrder = {
    "прСвУведомл",
    "свУведомл",
    "свДокИн"
})
public class СведЕГРРазд2Тип {

    @XmlElement(name = "ПрСвУведомл")
    protected String прСвУведомл;
    @XmlElement(name = "СвУведомл")
    protected СвУведомл свУведомл;
    @XmlElement(name = "СвДокИн", required = true)
    protected СвДокИн свДокИн;

    /**
     * Gets the value of the прСвУведомл property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрСвУведомл() {
        return прСвУведомл;
    }

    /**
     * Sets the value of the прСвУведомл property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрСвУведомл(String value) {
        this.прСвУведомл = value;
    }

    /**
     * Gets the value of the свУведомл property.
     * 
     * @return
     *     possible object is
     *     {@link СвУведомл }
     *     
     */
    public СвУведомл getСвУведомл() {
        return свУведомл;
    }

    /**
     * Sets the value of the свУведомл property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвУведомл }
     *     
     */
    public void setСвУведомл(СвУведомл value) {
        this.свУведомл = value;
    }

    /**
     * Gets the value of the свДокИн property.
     * 
     * @return
     *     possible object is
     *     {@link СвДокИн }
     *     
     */
    public СвДокИн getСвДокИн() {
        return свДокИн;
    }

    /**
     * Sets the value of the свДокИн property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвДокИн }
     *     
     */
    public void setСвДокИн(СвДокИн value) {
        this.свДокИн = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;choice&gt;
     *           &lt;element name="ПрКодОКСМ"&gt;
     *             &lt;simpleType&gt;
     *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                 &lt;enumeration value="1"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/simpleType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="КодОКСМ" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОКСМТип"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element name="НаимСтраны" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
     *         &lt;element name="РеквизИнДок"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрНаимДокТекст"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="НаимДокТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрНомер"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="Номер" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-100"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрДата"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="ДатаКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                     &lt;element name="ДатаДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрНаимОрган"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="НаимОрган" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="ТипДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-5" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ЮрЗначДок"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрПодпИн"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="СвПодпТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрЗасвидДок"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="ЗасвидДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрЗасвидПеревод"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="ЗасвидПеревод" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="СвОтказЛегализ"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="Легализация"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;choice&gt;
     *                                 &lt;element name="ПрОрганЛегал"&gt;
     *                                   &lt;simpleType&gt;
     *                                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                                       &lt;enumeration value="1"/&gt;
     *                                     &lt;/restriction&gt;
     *                                   &lt;/simpleType&gt;
     *                                 &lt;/element&gt;
     *                                 &lt;element name="ОрганЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
     *                               &lt;/choice&gt;
     *                               &lt;choice&gt;
     *                                 &lt;element name="ПрДатаЛегал"&gt;
     *                                   &lt;simpleType&gt;
     *                                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                                       &lt;enumeration value="1"/&gt;
     *                                     &lt;/restriction&gt;
     *                                   &lt;/simpleType&gt;
     *                                 &lt;/element&gt;
     *                                 &lt;element name="ДатаЛегал" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                               &lt;/choice&gt;
     *                               &lt;choice&gt;
     *                                 &lt;element name="ПрНомерЛегал"&gt;
     *                                   &lt;simpleType&gt;
     *                                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                                       &lt;enumeration value="1"/&gt;
     *                                     &lt;/restriction&gt;
     *                                   &lt;/simpleType&gt;
     *                                 &lt;/element&gt;
     *                                 &lt;element name="НомерЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-25"/&gt;
     *                               &lt;/choice&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="КолЛистДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-3" /&gt;
     *                 &lt;attribute name="СвОттискПеч" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                       &lt;enumeration value="1"/&gt;
     *                       &lt;enumeration value="2"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="СвЛегал" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                       &lt;enumeration value="1"/&gt;
     *                       &lt;enumeration value="2"/&gt;
     *                       &lt;enumeration value="3"/&gt;
     *                       &lt;enumeration value="4"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "прКодОКСМ",
        "кодОКСМ",
        "наимСтраны",
        "реквизИнДок",
        "юрЗначДок"
    })
    public static class СвДокИн {

        @XmlElement(name = "ПрКодОКСМ")
        protected String прКодОКСМ;
        @XmlElement(name = "КодОКСМ")
        protected String кодОКСМ;
        @XmlElement(name = "НаимСтраны", required = true)
        protected String наимСтраны;
        @XmlElement(name = "РеквизИнДок", required = true)
        protected РеквизИнДок реквизИнДок;
        @XmlElement(name = "ЮрЗначДок", required = true)
        protected ЮрЗначДок юрЗначДок;

        /**
         * Gets the value of the прКодОКСМ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getПрКодОКСМ() {
            return прКодОКСМ;
        }

        /**
         * Sets the value of the прКодОКСМ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setПрКодОКСМ(String value) {
            this.прКодОКСМ = value;
        }

        /**
         * Gets the value of the кодОКСМ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКодОКСМ() {
            return кодОКСМ;
        }

        /**
         * Sets the value of the кодОКСМ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКодОКСМ(String value) {
            this.кодОКСМ = value;
        }

        /**
         * Gets the value of the наимСтраны property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаимСтраны() {
            return наимСтраны;
        }

        /**
         * Sets the value of the наимСтраны property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаимСтраны(String value) {
            this.наимСтраны = value;
        }

        /**
         * Gets the value of the реквизИнДок property.
         * 
         * @return
         *     possible object is
         *     {@link РеквизИнДок }
         *     
         */
        public РеквизИнДок getРеквизИнДок() {
            return реквизИнДок;
        }

        /**
         * Sets the value of the реквизИнДок property.
         * 
         * @param value
         *     allowed object is
         *     {@link РеквизИнДок }
         *     
         */
        public void setРеквизИнДок(РеквизИнДок value) {
            this.реквизИнДок = value;
        }

        /**
         * Gets the value of the юрЗначДок property.
         * 
         * @return
         *     possible object is
         *     {@link ЮрЗначДок }
         *     
         */
        public ЮрЗначДок getЮрЗначДок() {
            return юрЗначДок;
        }

        /**
         * Sets the value of the юрЗначДок property.
         * 
         * @param value
         *     allowed object is
         *     {@link ЮрЗначДок }
         *     
         */
        public void setЮрЗначДок(ЮрЗначДок value) {
            this.юрЗначДок = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрНаимДокТекст"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="НаимДокТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрНомер"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="Номер" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-100"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрДата"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="ДатаКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *           &lt;element name="ДатаДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрНаимОрган"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="НаимОрган" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="ТипДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-5" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "прНаимДокТекст",
            "наимДокТекст",
            "прНомер",
            "номер",
            "прДата",
            "датаКаленд",
            "датаДок",
            "прНаимОрган",
            "наимОрган"
        })
        public static class РеквизИнДок {

            @XmlElement(name = "ПрНаимДокТекст")
            protected String прНаимДокТекст;
            @XmlElement(name = "НаимДокТекст")
            protected String наимДокТекст;
            @XmlElement(name = "ПрНомер")
            protected String прНомер;
            @XmlElement(name = "Номер")
            protected String номер;
            @XmlElement(name = "ПрДата")
            protected String прДата;
            @XmlElement(name = "ДатаКаленд")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar датаКаленд;
            @XmlElement(name = "ДатаДок")
            protected ДатаДокТип датаДок;
            @XmlElement(name = "ПрНаимОрган")
            protected String прНаимОрган;
            @XmlElement(name = "НаимОрган")
            protected String наимОрган;
            @XmlAttribute(name = "ТипДок", required = true)
            protected String типДок;

            /**
             * Gets the value of the прНаимДокТекст property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрНаимДокТекст() {
                return прНаимДокТекст;
            }

            /**
             * Sets the value of the прНаимДокТекст property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрНаимДокТекст(String value) {
                this.прНаимДокТекст = value;
            }

            /**
             * Gets the value of the наимДокТекст property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНаимДокТекст() {
                return наимДокТекст;
            }

            /**
             * Sets the value of the наимДокТекст property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНаимДокТекст(String value) {
                this.наимДокТекст = value;
            }

            /**
             * Gets the value of the прНомер property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрНомер() {
                return прНомер;
            }

            /**
             * Sets the value of the прНомер property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрНомер(String value) {
                this.прНомер = value;
            }

            /**
             * Gets the value of the номер property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНомер() {
                return номер;
            }

            /**
             * Sets the value of the номер property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНомер(String value) {
                this.номер = value;
            }

            /**
             * Gets the value of the прДата property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрДата() {
                return прДата;
            }

            /**
             * Sets the value of the прДата property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрДата(String value) {
                this.прДата = value;
            }

            /**
             * Gets the value of the датаКаленд property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаКаленд() {
                return датаКаленд;
            }

            /**
             * Sets the value of the датаКаленд property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаКаленд(XMLGregorianCalendar value) {
                this.датаКаленд = value;
            }

            /**
             * Gets the value of the датаДок property.
             * 
             * @return
             *     possible object is
             *     {@link ДатаДокТип }
             *     
             */
            public ДатаДокТип getДатаДок() {
                return датаДок;
            }

            /**
             * Sets the value of the датаДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link ДатаДокТип }
             *     
             */
            public void setДатаДок(ДатаДокТип value) {
                this.датаДок = value;
            }

            /**
             * Gets the value of the прНаимОрган property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрНаимОрган() {
                return прНаимОрган;
            }

            /**
             * Sets the value of the прНаимОрган property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрНаимОрган(String value) {
                this.прНаимОрган = value;
            }

            /**
             * Gets the value of the наимОрган property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНаимОрган() {
                return наимОрган;
            }

            /**
             * Sets the value of the наимОрган property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНаимОрган(String value) {
                this.наимОрган = value;
            }

            /**
             * Gets the value of the типДок property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getТипДок() {
                return типДок;
            }

            /**
             * Sets the value of the типДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setТипДок(String value) {
                this.типДок = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрПодпИн"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="СвПодпТекст" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрЗасвидДок"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="ЗасвидДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрЗасвидПеревод"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="ЗасвидПеревод" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ЗасвидТип"/&gt;
         *         &lt;/choice&gt;
         *         &lt;choice&gt;
         *           &lt;element name="СвОтказЛегализ"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="Легализация"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;choice&gt;
         *                       &lt;element name="ПрОрганЛегал"&gt;
         *                         &lt;simpleType&gt;
         *                           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                             &lt;enumeration value="1"/&gt;
         *                           &lt;/restriction&gt;
         *                         &lt;/simpleType&gt;
         *                       &lt;/element&gt;
         *                       &lt;element name="ОрганЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
         *                     &lt;/choice&gt;
         *                     &lt;choice&gt;
         *                       &lt;element name="ПрДатаЛегал"&gt;
         *                         &lt;simpleType&gt;
         *                           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                             &lt;enumeration value="1"/&gt;
         *                           &lt;/restriction&gt;
         *                         &lt;/simpleType&gt;
         *                       &lt;/element&gt;
         *                       &lt;element name="ДатаЛегал" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                     &lt;/choice&gt;
         *                     &lt;choice&gt;
         *                       &lt;element name="ПрНомерЛегал"&gt;
         *                         &lt;simpleType&gt;
         *                           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                             &lt;enumeration value="1"/&gt;
         *                           &lt;/restriction&gt;
         *                         &lt;/simpleType&gt;
         *                       &lt;/element&gt;
         *                       &lt;element name="НомерЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-25"/&gt;
         *                     &lt;/choice&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="КолЛистДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-3" /&gt;
         *       &lt;attribute name="СвОттискПеч" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *             &lt;enumeration value="1"/&gt;
         *             &lt;enumeration value="2"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="СвЛегал" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *             &lt;enumeration value="1"/&gt;
         *             &lt;enumeration value="2"/&gt;
         *             &lt;enumeration value="3"/&gt;
         *             &lt;enumeration value="4"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "прПодпИн",
            "свПодпТекст",
            "прЗасвидДок",
            "засвидДок",
            "прЗасвидПеревод",
            "засвидПеревод",
            "свОтказЛегализ",
            "легализация"
        })
        public static class ЮрЗначДок {

            @XmlElement(name = "ПрПодпИн")
            protected String прПодпИн;
            @XmlElement(name = "СвПодпТекст")
            protected String свПодпТекст;
            @XmlElement(name = "ПрЗасвидДок")
            protected String прЗасвидДок;
            @XmlElement(name = "ЗасвидДок")
            protected ЗасвидТип засвидДок;
            @XmlElement(name = "ПрЗасвидПеревод")
            protected String прЗасвидПеревод;
            @XmlElement(name = "ЗасвидПеревод")
            protected ЗасвидТип засвидПеревод;
            @XmlElement(name = "СвОтказЛегализ")
            protected String свОтказЛегализ;
            @XmlElement(name = "Легализация")
            protected Легализация легализация;
            @XmlAttribute(name = "КолЛистДок")
            protected BigInteger колЛистДок;
            @XmlAttribute(name = "СвОттискПеч", required = true)
            protected String свОттискПеч;
            @XmlAttribute(name = "СвЛегал", required = true)
            protected String свЛегал;

            /**
             * Gets the value of the прПодпИн property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрПодпИн() {
                return прПодпИн;
            }

            /**
             * Sets the value of the прПодпИн property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрПодпИн(String value) {
                this.прПодпИн = value;
            }

            /**
             * Gets the value of the свПодпТекст property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСвПодпТекст() {
                return свПодпТекст;
            }

            /**
             * Sets the value of the свПодпТекст property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСвПодпТекст(String value) {
                this.свПодпТекст = value;
            }

            /**
             * Gets the value of the прЗасвидДок property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрЗасвидДок() {
                return прЗасвидДок;
            }

            /**
             * Sets the value of the прЗасвидДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрЗасвидДок(String value) {
                this.прЗасвидДок = value;
            }

            /**
             * Gets the value of the засвидДок property.
             * 
             * @return
             *     possible object is
             *     {@link ЗасвидТип }
             *     
             */
            public ЗасвидТип getЗасвидДок() {
                return засвидДок;
            }

            /**
             * Sets the value of the засвидДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link ЗасвидТип }
             *     
             */
            public void setЗасвидДок(ЗасвидТип value) {
                this.засвидДок = value;
            }

            /**
             * Gets the value of the прЗасвидПеревод property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрЗасвидПеревод() {
                return прЗасвидПеревод;
            }

            /**
             * Sets the value of the прЗасвидПеревод property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрЗасвидПеревод(String value) {
                this.прЗасвидПеревод = value;
            }

            /**
             * Gets the value of the засвидПеревод property.
             * 
             * @return
             *     possible object is
             *     {@link ЗасвидТип }
             *     
             */
            public ЗасвидТип getЗасвидПеревод() {
                return засвидПеревод;
            }

            /**
             * Sets the value of the засвидПеревод property.
             * 
             * @param value
             *     allowed object is
             *     {@link ЗасвидТип }
             *     
             */
            public void setЗасвидПеревод(ЗасвидТип value) {
                this.засвидПеревод = value;
            }

            /**
             * Gets the value of the свОтказЛегализ property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСвОтказЛегализ() {
                return свОтказЛегализ;
            }

            /**
             * Sets the value of the свОтказЛегализ property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСвОтказЛегализ(String value) {
                this.свОтказЛегализ = value;
            }

            /**
             * Gets the value of the легализация property.
             * 
             * @return
             *     possible object is
             *     {@link Легализация }
             *     
             */
            public Легализация getЛегализация() {
                return легализация;
            }

            /**
             * Sets the value of the легализация property.
             * 
             * @param value
             *     allowed object is
             *     {@link Легализация }
             *     
             */
            public void setЛегализация(Легализация value) {
                this.легализация = value;
            }

            /**
             * Gets the value of the колЛистДок property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getКолЛистДок() {
                return колЛистДок;
            }

            /**
             * Sets the value of the колЛистДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setКолЛистДок(BigInteger value) {
                this.колЛистДок = value;
            }

            /**
             * Gets the value of the свОттискПеч property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСвОттискПеч() {
                return свОттискПеч;
            }

            /**
             * Sets the value of the свОттискПеч property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСвОттискПеч(String value) {
                this.свОттискПеч = value;
            }

            /**
             * Gets the value of the свЛегал property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСвЛегал() {
                return свЛегал;
            }

            /**
             * Sets the value of the свЛегал property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСвЛегал(String value) {
                this.свЛегал = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;choice&gt;
             *           &lt;element name="ПрОрганЛегал"&gt;
             *             &lt;simpleType&gt;
             *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
             *                 &lt;enumeration value="1"/&gt;
             *               &lt;/restriction&gt;
             *             &lt;/simpleType&gt;
             *           &lt;/element&gt;
             *           &lt;element name="ОрганЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
             *         &lt;/choice&gt;
             *         &lt;choice&gt;
             *           &lt;element name="ПрДатаЛегал"&gt;
             *             &lt;simpleType&gt;
             *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
             *                 &lt;enumeration value="1"/&gt;
             *               &lt;/restriction&gt;
             *             &lt;/simpleType&gt;
             *           &lt;/element&gt;
             *           &lt;element name="ДатаЛегал" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;/choice&gt;
             *         &lt;choice&gt;
             *           &lt;element name="ПрНомерЛегал"&gt;
             *             &lt;simpleType&gt;
             *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
             *                 &lt;enumeration value="1"/&gt;
             *               &lt;/restriction&gt;
             *             &lt;/simpleType&gt;
             *           &lt;/element&gt;
             *           &lt;element name="НомерЛегал" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-25"/&gt;
             *         &lt;/choice&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "прОрганЛегал",
                "органЛегал",
                "прДатаЛегал",
                "датаЛегал",
                "прНомерЛегал",
                "номерЛегал"
            })
            public static class Легализация {

                @XmlElement(name = "ПрОрганЛегал")
                protected String прОрганЛегал;
                @XmlElement(name = "ОрганЛегал")
                protected String органЛегал;
                @XmlElement(name = "ПрДатаЛегал")
                protected String прДатаЛегал;
                @XmlElement(name = "ДатаЛегал")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar датаЛегал;
                @XmlElement(name = "ПрНомерЛегал")
                protected String прНомерЛегал;
                @XmlElement(name = "НомерЛегал")
                protected String номерЛегал;

                /**
                 * Gets the value of the прОрганЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getПрОрганЛегал() {
                    return прОрганЛегал;
                }

                /**
                 * Sets the value of the прОрганЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setПрОрганЛегал(String value) {
                    this.прОрганЛегал = value;
                }

                /**
                 * Gets the value of the органЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getОрганЛегал() {
                    return органЛегал;
                }

                /**
                 * Sets the value of the органЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setОрганЛегал(String value) {
                    this.органЛегал = value;
                }

                /**
                 * Gets the value of the прДатаЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getПрДатаЛегал() {
                    return прДатаЛегал;
                }

                /**
                 * Sets the value of the прДатаЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setПрДатаЛегал(String value) {
                    this.прДатаЛегал = value;
                }

                /**
                 * Gets the value of the датаЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getДатаЛегал() {
                    return датаЛегал;
                }

                /**
                 * Sets the value of the датаЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setДатаЛегал(XMLGregorianCalendar value) {
                    this.датаЛегал = value;
                }

                /**
                 * Gets the value of the прНомерЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getПрНомерЛегал() {
                    return прНомерЛегал;
                }

                /**
                 * Sets the value of the прНомерЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setПрНомерЛегал(String value) {
                    this.прНомерЛегал = value;
                }

                /**
                 * Gets the value of the номерЛегал property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getНомерЛегал() {
                    return номерЛегал;
                }

                /**
                 * Sets the value of the номерЛегал property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setНомерЛегал(String value) {
                    this.номерЛегал = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;choice&gt;
     *           &lt;element name="ПрКодВидУвед"&gt;
     *             &lt;simpleType&gt;
     *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                 &lt;enumeration value="1"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/simpleType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="КодВидУвед" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-5"/&gt;
     *         &lt;/choice&gt;
     *         &lt;choice&gt;
     *           &lt;element name="ПрДатаУвед"&gt;
     *             &lt;simpleType&gt;
     *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                 &lt;enumeration value="1"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/simpleType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="ДатаУвед" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element name="СведЗАГСУвед"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСТип"/&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрФИООтв"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="ФИООтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="ДатаПринят" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="ДолжнОтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="СпоcПод" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *             &lt;enumeration value="1"/&gt;
     *             &lt;enumeration value="2"/&gt;
     *             &lt;enumeration value="3"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="КолЛистДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-3" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "прКодВидУвед",
        "кодВидУвед",
        "прДатаУвед",
        "датаУвед",
        "сведЗАГСУвед"
    })
    public static class СвУведомл {

        @XmlElement(name = "ПрКодВидУвед")
        protected String прКодВидУвед;
        @XmlElement(name = "КодВидУвед")
        protected String кодВидУвед;
        @XmlElement(name = "ПрДатаУвед")
        protected String прДатаУвед;
        @XmlElement(name = "ДатаУвед")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar датаУвед;
        @XmlElement(name = "СведЗАГСУвед", required = true)
        protected СведЗАГСУвед сведЗАГСУвед;
        @XmlAttribute(name = "СпоcПод", required = true)
        protected String споcПод;
        @XmlAttribute(name = "КолЛистДок")
        protected BigInteger колЛистДок;

        /**
         * Gets the value of the прКодВидУвед property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getПрКодВидУвед() {
            return прКодВидУвед;
        }

        /**
         * Sets the value of the прКодВидУвед property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setПрКодВидУвед(String value) {
            this.прКодВидУвед = value;
        }

        /**
         * Gets the value of the кодВидУвед property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКодВидУвед() {
            return кодВидУвед;
        }

        /**
         * Sets the value of the кодВидУвед property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКодВидУвед(String value) {
            this.кодВидУвед = value;
        }

        /**
         * Gets the value of the прДатаУвед property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getПрДатаУвед() {
            return прДатаУвед;
        }

        /**
         * Sets the value of the прДатаУвед property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setПрДатаУвед(String value) {
            this.прДатаУвед = value;
        }

        /**
         * Gets the value of the датаУвед property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getДатаУвед() {
            return датаУвед;
        }

        /**
         * Sets the value of the датаУвед property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setДатаУвед(XMLGregorianCalendar value) {
            this.датаУвед = value;
        }

        /**
         * Gets the value of the сведЗАГСУвед property.
         * 
         * @return
         *     possible object is
         *     {@link СведЗАГСУвед }
         *     
         */
        public СведЗАГСУвед getСведЗАГСУвед() {
            return сведЗАГСУвед;
        }

        /**
         * Sets the value of the сведЗАГСУвед property.
         * 
         * @param value
         *     allowed object is
         *     {@link СведЗАГСУвед }
         *     
         */
        public void setСведЗАГСУвед(СведЗАГСУвед value) {
            this.сведЗАГСУвед = value;
        }

        /**
         * Gets the value of the споcПод property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getСпоcПод() {
            return споcПод;
        }

        /**
         * Sets the value of the споcПод property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setСпоcПод(String value) {
            this.споcПод = value;
        }

        /**
         * Gets the value of the колЛистДок property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getКолЛистДок() {
            return колЛистДок;
        }

        /**
         * Sets the value of the колЛистДок property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setКолЛистДок(BigInteger value) {
            this.колЛистДок = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСТип"/&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрФИООтв"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="ФИООтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="ДатаПринят" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="ДолжнОтв" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-255" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "органЗАГС",
            "прФИООтв",
            "фиоОтв"
        })
        public static class СведЗАГСУвед {

            @XmlElement(name = "ОрганЗАГС", required = true)
            protected ОрганЗАГСТип органЗАГС;
            @XmlElement(name = "ПрФИООтв")
            protected String прФИООтв;
            @XmlElement(name = "ФИООтв")
            protected ФИОПрТип фиоОтв;
            @XmlAttribute(name = "ДатаПринят", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar датаПринят;
            @XmlAttribute(name = "ДолжнОтв")
            protected String должнОтв;

            /**
             * Gets the value of the органЗАГС property.
             * 
             * @return
             *     possible object is
             *     {@link ОрганЗАГСТип }
             *     
             */
            public ОрганЗАГСТип getОрганЗАГС() {
                return органЗАГС;
            }

            /**
             * Sets the value of the органЗАГС property.
             * 
             * @param value
             *     allowed object is
             *     {@link ОрганЗАГСТип }
             *     
             */
            public void setОрганЗАГС(ОрганЗАГСТип value) {
                this.органЗАГС = value;
            }

            /**
             * Gets the value of the прФИООтв property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрФИООтв() {
                return прФИООтв;
            }

            /**
             * Sets the value of the прФИООтв property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрФИООтв(String value) {
                this.прФИООтв = value;
            }

            /**
             * Gets the value of the фиоОтв property.
             * 
             * @return
             *     possible object is
             *     {@link ФИОПрТип }
             *     
             */
            public ФИОПрТип getФИООтв() {
                return фиоОтв;
            }

            /**
             * Sets the value of the фиоОтв property.
             * 
             * @param value
             *     allowed object is
             *     {@link ФИОПрТип }
             *     
             */
            public void setФИООтв(ФИОПрТип value) {
                this.фиоОтв = value;
            }

            /**
             * Gets the value of the датаПринят property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаПринят() {
                return датаПринят;
            }

            /**
             * Sets the value of the датаПринят property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаПринят(XMLGregorianCalendar value) {
                this.датаПринят = value;
            }

            /**
             * Gets the value of the должнОтв property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getДолжнОтв() {
                return должнОтв;
            }

            /**
             * Sets the value of the должнОтв property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setДолжнОтв(String value) {
                this.должнОтв = value;
            }

        }

    }

}
