//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.xmls.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Фамилия, имя, отчество физического лица (с признаком отсутствия)
 * 
 * <p>Java class for ФИОПрТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ФИОПрТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Фамилия" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-60"/&gt;
 *           &lt;element name="ПрФамилия"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Имя" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-60"/&gt;
 *           &lt;element name="ПрИмя"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Отчество" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-60"/&gt;
 *           &lt;element name="ПрОтчество"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                 &lt;enumeration value="1"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ФИОПрТип", propOrder = {
    "фамилия",
    "прФамилия",
    "имя",
    "прИмя",
    "отчество",
    "прОтчество"
})
public class ФИОПрТип {

    @XmlElement(name = "Фамилия")
    protected String фамилия;
    @XmlElement(name = "ПрФамилия")
    protected String прФамилия;
    @XmlElement(name = "Имя")
    protected String имя;
    @XmlElement(name = "ПрИмя")
    protected String прИмя;
    @XmlElement(name = "Отчество")
    protected String отчество;
    @XmlElement(name = "ПрОтчество")
    protected String прОтчество;

    /**
     * Gets the value of the фамилия property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getФамилия() {
        return фамилия;
    }

    /**
     * Sets the value of the фамилия property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setФамилия(String value) {
        this.фамилия = value;
    }

    /**
     * Gets the value of the прФамилия property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрФамилия() {
        return прФамилия;
    }

    /**
     * Sets the value of the прФамилия property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрФамилия(String value) {
        this.прФамилия = value;
    }

    /**
     * Gets the value of the имя property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИмя() {
        return имя;
    }

    /**
     * Sets the value of the имя property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИмя(String value) {
        this.имя = value;
    }

    /**
     * Gets the value of the прИмя property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрИмя() {
        return прИмя;
    }

    /**
     * Sets the value of the прИмя property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрИмя(String value) {
        this.прИмя = value;
    }

    /**
     * Gets the value of the отчество property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОтчество() {
        return отчество;
    }

    /**
     * Sets the value of the отчество property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОтчество(String value) {
        this.отчество = value;
    }

    /**
     * Gets the value of the прОтчество property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрОтчество() {
        return прОтчество;
    }

    /**
     * Sets the value of the прОтчество property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрОтчество(String value) {
        this.прОтчество = value;
    }

}
