//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.xmls.root;



import com.example.demo.models.xmls.types.ДатаДокТип;
import com.example.demo.models.xmls.types.ОрганЗАГСНТип;
import com.example.demo.models.xmls.types.УдЛичнФЛСНТип;
import com.example.demo.models.xmls.types.ФИОПрТип;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="СведОсн"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="СведДокОсн" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
 *                   &lt;element name="ПрСведДокОсн"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                         &lt;enumeration value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="КодНормОсн" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-2" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="СведЗапрос" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="СведАГС" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ДатаЗаписДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
 *                               &lt;element name="ДатаЗапис" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСНТип"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="НомерЗапис" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-22" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="СведФЛ"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ФИО" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="ПрДатаРожд"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                                     &lt;enumeration value="1"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="ДатаРождКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                               &lt;element name="ДатаРождДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
 *                             &lt;/choice&gt;
 *                             &lt;element name="УдЛичнФЛ" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}УдЛичнФЛСНТип" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="СНИЛС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}СНИЛСТип" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="ПрРегионРегАГС"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
 *                           &lt;enumeration value="1"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="РегионРегАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ССРФТип"/&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="ИдДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-36" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ИдЗапросТип" /&gt;
 *       &lt;attribute name="КолДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}number-2" /&gt;
 *       &lt;attribute name="ТипАГС" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-2"&gt;
 *             &lt;enumeration value="07"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
    "сведОсн",
    "сведЗапрос"
})
@XmlRootElement(name = "FATALINFRequest")
public class FATALINFRequest {

    @XmlElement(name = "СведОсн", required = true)
    protected СведОсн сведОсн;
    @XmlElement(name = "СведЗапрос", required = true)
    protected List<СведЗапрос> сведЗапрос;
    @XmlAttribute(name = "ИдЗапрос", required = true)
    protected String идЗапрос;
    @XmlAttribute(name = "КолДок", required = true)
    protected BigInteger колДок;
    @XmlAttribute(name = "ТипАГС", required = true)
    protected String типАГС;

    /**
     * Gets the value of the сведОсн property.
     * 
     * @return
     *     possible object is
     *     {@link СведОсн }
     *     
     */
    public СведОсн getСведОсн() {
        return сведОсн;
    }

    /**
     * Sets the value of the сведОсн property.
     * 
     * @param value
     *     allowed object is
     *     {@link СведОсн }
     *     
     */
    public void setСведОсн(СведОсн value) {
        this.сведОсн = value;
    }

    /**
     * Gets the value of the сведЗапрос property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the сведЗапрос property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getСведЗапрос().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link СведЗапрос }
     * 
     * 
     */
    public List<СведЗапрос> getСведЗапрос() {
        if (сведЗапрос == null) {
            сведЗапрос = new ArrayList<СведЗапрос>();
        }
        return this.сведЗапрос;
    }

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }

    /**
     * Gets the value of the колДок property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getКолДок() {
        return колДок;
    }

    /**
     * Sets the value of the колДок property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setКолДок(BigInteger value) {
        this.колДок = value;
    }

    /**
     * Gets the value of the типАГС property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getТипАГС() {
        return типАГС;
    }

    /**
     * Sets the value of the типАГС property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setТипАГС(String value) {
        this.типАГС = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="СведАГС" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ДатаЗаписДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
     *                     &lt;element name="ДатаЗапис" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСНТип"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="НомерЗапис" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-22" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="СведФЛ"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ФИО" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="ПрДатаРожд"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                           &lt;enumeration value="1"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="ДатаРождКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                     &lt;element name="ДатаРождДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
     *                   &lt;/choice&gt;
     *                   &lt;element name="УдЛичнФЛ" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}УдЛичнФЛСНТип" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="СНИЛС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}СНИЛСТип" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;choice&gt;
     *           &lt;element name="ПрРегионРегАГС"&gt;
     *             &lt;simpleType&gt;
     *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *                 &lt;enumeration value="1"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/simpleType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="РегионРегАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ССРФТип"/&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="ИдДок" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-36" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType( propOrder = {
        "сведАГС",
        "сведФЛ",
        "прРегионРегАГС",
        "регионРегАГС"
    })
    public static class СведЗапрос {

        @XmlElement(name = "СведАГС")
        protected СведАГС сведАГС;
        @XmlElement(name = "СведФЛ", required = true)
        protected СведФЛ сведФЛ;
        @XmlElement(name = "ПрРегионРегАГС")
        protected String прРегионРегАГС;
        @XmlElement(name = "РегионРегАГС")
        protected String регионРегАГС;
        @XmlAttribute(name = "ИдДок", required = true)
        protected String идДок;

        /**
         * Gets the value of the сведАГС property.
         * 
         * @return
         *     possible object is
         *     {@link СведАГС }
         *     
         */
        public СведАГС getСведАГС() {
            return сведАГС;
        }

        /**
         * Sets the value of the сведАГС property.
         * 
         * @param value
         *     allowed object is
         *     {@link СведАГС }
         *     
         */
        public void setСведАГС(СведАГС value) {
            this.сведАГС = value;
        }

        /**
         * Gets the value of the сведФЛ property.
         * 
         * @return
         *     possible object is
         *     {@link СведФЛ }
         *     
         */
        public СведФЛ getСведФЛ() {
            return сведФЛ;
        }

        /**
         * Sets the value of the сведФЛ property.
         * 
         * @param value
         *     allowed object is
         *     {@link СведФЛ }
         *     
         */
        public void setСведФЛ(СведФЛ value) {
            this.сведФЛ = value;
        }

        /**
         * Gets the value of the прРегионРегАГС property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getПрРегионРегАГС() {
            return прРегионРегАГС;
        }

        /**
         * Sets the value of the прРегионРегАГС property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setПрРегионРегАГС(String value) {
            this.прРегионРегАГС = value;
        }

        /**
         * Gets the value of the регионРегАГС property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getРегионРегАГС() {
            return регионРегАГС;
        }

        /**
         * Sets the value of the регионРегАГС property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setРегионРегАГС(String value) {
            this.регионРегАГС = value;
        }

        /**
         * Gets the value of the идДок property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИдДок() {
            return идДок;
        }

        /**
         * Sets the value of the идДок property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИдДок(String value) {
            this.идДок = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ДатаЗаписДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
         *           &lt;element name="ДатаЗапис" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;/choice&gt;
         *         &lt;element name="ОрганЗАГС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ОрганЗАГСНТип"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="НомерЗапис" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-22" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType( propOrder = {
            "датаЗаписДок",
            "датаЗапис",
            "органЗАГС"
        })
        public static class СведАГС {

            @XmlElement(name = "ДатаЗаписДок")
            protected ДатаДокТип датаЗаписДок;
            @XmlElement(name = "ДатаЗапис")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar датаЗапис;
            @XmlElement(name = "ОрганЗАГС", required = true)
            protected ОрганЗАГСНТип органЗАГС;
            @XmlAttribute(name = "НомерЗапис", required = true)
            protected String номерЗапис;

            /**
             * Gets the value of the датаЗаписДок property.
             * 
             * @return
             *     possible object is
             *     {@link ДатаДокТип }
             *     
             */
            public ДатаДокТип getДатаЗаписДок() {
                return датаЗаписДок;
            }

            /**
             * Sets the value of the датаЗаписДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link ДатаДокТип }
             *     
             */
            public void setДатаЗаписДок(ДатаДокТип value) {
                this.датаЗаписДок = value;
            }

            /**
             * Gets the value of the датаЗапис property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаЗапис() {
                return датаЗапис;
            }

            /**
             * Sets the value of the датаЗапис property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаЗапис(XMLGregorianCalendar value) {
                this.датаЗапис = value;
            }

            /**
             * Gets the value of the органЗАГС property.
             * 
             * @return
             *     possible object is
             *     {@link ОрганЗАГСНТип }
             *     
             */
            public ОрганЗАГСНТип getОрганЗАГС() {
                return органЗАГС;
            }

            /**
             * Sets the value of the органЗАГС property.
             * 
             * @param value
             *     allowed object is
             *     {@link ОрганЗАГСНТип }
             *     
             */
            public void setОрганЗАГС(ОрганЗАГСНТип value) {
                this.органЗАГС = value;
            }

            /**
             * Gets the value of the номерЗапис property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНомерЗапис() {
                return номерЗапис;
            }

            /**
             * Sets the value of the номерЗапис property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНомерЗапис(String value) {
                this.номерЗапис = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ФИО" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ФИОПрТип"/&gt;
         *         &lt;choice&gt;
         *           &lt;element name="ПрДатаРожд"&gt;
         *             &lt;simpleType&gt;
         *               &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
         *                 &lt;enumeration value="1"/&gt;
         *               &lt;/restriction&gt;
         *             &lt;/simpleType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="ДатаРождКаленд" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *           &lt;element name="ДатаРождДок" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}ДатаДокТип"/&gt;
         *         &lt;/choice&gt;
         *         &lt;element name="УдЛичнФЛ" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}УдЛичнФЛСНТип" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="СНИЛС" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}СНИЛСТип" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(propOrder = {
            "фио",
            "прДатаРожд",
            "датаРождКаленд",
            "датаРождДок",
            "удЛичнФЛ"
        })
        public static class СведФЛ {

            @XmlElement(name = "ФИО", required = true)
            protected ФИОПрТип фио;
            @XmlElement(name = "ПрДатаРожд")
            protected String прДатаРожд;
            @XmlElement(name = "ДатаРождКаленд")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar датаРождКаленд;
            @XmlElement(name = "ДатаРождДок")
            protected ДатаДокТип датаРождДок;
            @XmlElement(name = "УдЛичнФЛ")
            protected УдЛичнФЛСНТип удЛичнФЛ;
            @XmlAttribute(name = "СНИЛС")
            protected String снилс;

            /**
             * Gets the value of the фио property.
             * 
             * @return
             *     possible object is
             *     {@link ФИОПрТип }
             *     
             */
            public ФИОПрТип getФИО() {
                return фио;
            }

            /**
             * Sets the value of the фио property.
             * 
             * @param value
             *     allowed object is
             *     {@link ФИОПрТип }
             *     
             */
            public void setФИО(ФИОПрТип value) {
                this.фио = value;
            }

            /**
             * Gets the value of the прДатаРожд property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getПрДатаРожд() {
                return прДатаРожд;
            }

            /**
             * Sets the value of the прДатаРожд property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setПрДатаРожд(String value) {
                this.прДатаРожд = value;
            }

            /**
             * Gets the value of the датаРождКаленд property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаРождКаленд() {
                return датаРождКаленд;
            }

            /**
             * Sets the value of the датаРождКаленд property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаРождКаленд(XMLGregorianCalendar value) {
                this.датаРождКаленд = value;
            }

            /**
             * Gets the value of the датаРождДок property.
             * 
             * @return
             *     possible object is
             *     {@link ДатаДокТип }
             *     
             */
            public ДатаДокТип getДатаРождДок() {
                return датаРождДок;
            }

            /**
             * Sets the value of the датаРождДок property.
             * 
             * @param value
             *     allowed object is
             *     {@link ДатаДокТип }
             *     
             */
            public void setДатаРождДок(ДатаДокТип value) {
                this.датаРождДок = value;
            }

            /**
             * Gets the value of the удЛичнФЛ property.
             * 
             * @return
             *     possible object is
             *     {@link УдЛичнФЛСНТип }
             *     
             */
            public УдЛичнФЛСНТип getУдЛичнФЛ() {
                return удЛичнФЛ;
            }

            /**
             * Sets the value of the удЛичнФЛ property.
             * 
             * @param value
             *     allowed object is
             *     {@link УдЛичнФЛСНТип }
             *     
             */
            public void setУдЛичнФЛ(УдЛичнФЛСНТип value) {
                this.удЛичнФЛ = value;
            }

            /**
             * Gets the value of the снилс property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСНИЛС() {
                return снилс;
            }

            /**
             * Sets the value of the снилс property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСНИЛС(String value) {
                this.снилс = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="СведДокОсн" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-500"/&gt;
     *         &lt;element name="ПрСведДокОсн"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-1"&gt;
     *               &lt;enumeration value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="КодНормОсн" use="required" type="{urn://x-artefacts-zags-fatalinf/types/4.0.1}string-2" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(propOrder = {
        "сведДокОсн",
        "прСведДокОсн"
    })
    public static class СведОсн {

        @XmlElement(name = "СведДокОсн")
        protected String сведДокОсн;
        @XmlElement(name = "ПрСведДокОсн")
        protected String прСведДокОсн;
        @XmlAttribute(name = "КодНормОсн", required = true)
        protected String кодНормОсн;

        /**
         * Gets the value of the сведДокОсн property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getСведДокОсн() {
            return сведДокОсн;
        }

        /**
         * Sets the value of the сведДокОсн property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setСведДокОсн(String value) {
            this.сведДокОсн = value;
        }

        /**
         * Gets the value of the прСведДокОсн property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getПрСведДокОсн() {
            return прСведДокОсн;
        }

        /**
         * Sets the value of the прСведДокОсн property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setПрСведДокОсн(String value) {
            this.прСведДокОсн = value;
        }

        /**
         * Gets the value of the кодНормОсн property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКодНормОсн() {
            return кодНормОсн;
        }

        /**
         * Sets the value of the кодНормОсн property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКодНормОсн(String value) {
            this.кодНормОсн = value;
        }

    }

}
