//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.31 at 01:01:39 PM GMT+07:00 
//


package com.example.demo.models.xmls.root;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fatalinf.zags.artefacts.x.root._112_52._4_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fatalinf.zags.artefacts.x.root._112_52._4_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FATALINFRequest }
     * 
     */
    public FATALINFRequest createFATALINFRequest() {
        return new FATALINFRequest();
    }

    /**
     * Create an instance of {@link FATALINFResponse }
     * 
     */
    public FATALINFResponse createFATALINFResponse() {
        return new FATALINFResponse();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС }
     * 
     */
    public FATALINFResponse.СведОтветАГС createFATALINFResponseСведОтветАГС() {
        return new FATALINFResponse.СведОтветАГС();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС.СведРегСмерт }
     * 
     */
    public FATALINFResponse.СведОтветАГС.СведРегСмерт createFATALINFResponseСведОтветАГССведРегСмерт() {
        return new FATALINFResponse.СведОтветАГС.СведРегСмерт();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег }
     * 
     */
    public FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег createFATALINFResponseСведОтветАГССведРегСмертПрдСведРег() {
        return new FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт }
     * 
     */
    public FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт createFATALINFResponseСведОтветАГССведРегСмертПрдСведРегСведПричСмерт() {
        return new FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт();
    }

    /**
     * Create an instance of {@link FATALINFRequest.СведЗапрос }
     * 
     */
    public FATALINFRequest.СведЗапрос createFATALINFRequestСведЗапрос() {
        return new FATALINFRequest.СведЗапрос();
    }

    /**
     * Create an instance of {@link FATALINFRequest.СведОсн }
     * 
     */
    public FATALINFRequest.СведОсн createFATALINFRequestСведОсн() {
        return new FATALINFRequest.СведОсн();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертМКБ }
     * 
     */
    public FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертМКБ createFATALINFResponseСведОтветАГССведРегСмертПрдСведРегСведПричСмертСвПричСмертМКБ() {
        return new FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертМКБ();
    }

    /**
     * Create an instance of {@link FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертПроизв }
     * 
     */
    public FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертПроизв createFATALINFResponseСведОтветАГССведРегСмертПрдСведРегСведПричСмертСвПричСмертПроизв() {
        return new FATALINFResponse.СведОтветАГС.СведРегСмерт.ПрдСведРег.СведПричСмерт.СвПричСмертПроизв();
    }

    /**
     * Create an instance of {@link FATALINFRequest.СведЗапрос.СведАГС }
     * 
     */
    public FATALINFRequest.СведЗапрос.СведАГС createFATALINFRequestСведЗапросСведАГС() {
        return new FATALINFRequest.СведЗапрос.СведАГС();
    }

    /**
     * Create an instance of {@link FATALINFRequest.СведЗапрос.СведФЛ }
     * 
     */
    public FATALINFRequest.СведЗапрос.СведФЛ createFATALINFRequestСведЗапросСведФЛ() {
        return new FATALINFRequest.СведЗапрос.СведФЛ();
    }

}
